By the end of this tutorial, you should be able to

* Find the eigenvalue/eigenvector pairs of a given matrix
* Find the inverse of a given matrix
* Find the matrix exponential
* Perform singular value decomposition
* Find the pseudoinverse of a rectangular matrix

There are five levels of comprehension that we will test in this class:
* Can I describe it? (descriptive)
* Can I express it mathematically? (theoretical)
* Can I do a hand calculation? (practical)
* Can I code it? (computational)
* Do I know when to use it? (application)

# Finding the eigenvalues/vectors of a given matrix

Finding the eigvenvalues and eigenvectors of a given matrix is one of the common operations with matrix math. Conceptually, For every square matrix $A$ there exists a number of scalar values $\lambda$ (an eigenvalue), that, when multiplied by a corresponding vector $\overrightarrow{\eta}$ will return the same vector:

$$A\overrightarrow{\eta} = \lambda \overrightarrow{\eta} $$

The question is: how do we find what these pair of eigvenvalues and eigenvectors for a given matrix? Doing a little rearranging gives:

$$(A-\lambda I) \overrightarrow{\eta} = \overrightarrow{0} $$

So, unless $\overrightarrow{\eta} = \overrightarrow{0}$ (which we don't want), then $(A-\lambda I)$ must be equal to zero. This can only happen when the matrix is singular (e.g. its determinant is equal to zero). Thus, the eigenvalues of a given matrix can be found by the equation:

$$\det{A-\lambda I} = 0$$

This can be written out like so for an example 3 x 3 matrix:

$$
  \det{
  \left[ {\begin{array}{ccc}
   3 - \lambda & 2 & 4\\
   2 & 0 - \lambda & 2\\
   4 & 2 & 3 - \lambda\\
  \end{array} } \right]} = 0$$

Writing this out gives the following polynomial:
    
$$-\lambda^3 + 6 \lambda^2 + 15 \lambda + 8 = 0$$

You may have a difficult time finding the roots to this equation. Conveniently, this matrix happens to be easy to solve using the Rational Roots Theorem. All the roots for this given matrix are rational:

$$(\lambda + 1)^2 (\lambda - 8) = 0 $$

Giving the eigenvalues $\lambda = -1, -1, 8 $.

The eigenvectors can then be found using row operations to convert the extended matrix into row echelon form after substituting in a given eigenvalue:

$$
  \left[ {\begin{array}{cccc}
   4 & 2 & 4 & 0\\
   2 & 1 & 2 & 0\\
   4 & 2 & 4 & 0\\
  \end{array} } \right]$$

But uh oh... it looks like all rows aren't linearly independent. In this case, there are actually an infinite possible amount of solutions, but all solutions can be expressed as:

$$y = -2x - 2z $$

Thus, all potential eigenvectors can be expressed as:

$$\langle s, -2s - 2t, t \rangle $$

The first one, we can just pick two easy numbers, say, s=0 and t=1: $<0, -2, 1>$. The second must be orthogonal to the first, which can be ensured using the dot product:

$$\langle 0, -2, 1 \rangle \cdot \langle s, -2s - 2t, t \rangle = 0$$

which gives the equation:

$$4s + 5t = 0 $$

This also has potentially infinite solutions, but we can pick s=-5 and t=4, giving $\langle -5, 2, 4 \rangle$

The final eigenvalue can be found by substituting $\lambda = 8$:

$$
  \left[ {\begin{array}{cccc}
   -5 & 2 & 4 & 0\\
   2 & -8 & 2 & 0\\
   4 & 2 & -5 & 0\\
  \end{array} } \right]$$

This also doesn't have a single solution, but we can fix one value arbitrarily (say y=1) and solve the system of equations to give the resulting eigenvector. After some math, it can be found that all potential vectors are of the form: $\langle 2r, r, 2r \rangle$. We can pick r=1 to give $\langle 2, 1, 2 \rangle$

Reducing our eigenvectors to unit vectors give the following eigenvalue/eigenvector sets:
    
$$\lambda = -1: \langle 0, \frac{-2}{\sqrt{5}}, \frac{1}{\sqrt{5}} \rangle$$
$$\lambda = -1: \langle \frac{-5}{\sqrt{45}}, \frac{2}{\sqrt{45}}, \frac{4}{\sqrt{45}} \rangle$$
$$\lambda = 8: \langle \frac{2}{3}, \frac{1}{3}, \frac{2}{3} \rangle$$

We found a valid set of eigenvectors for the given matrix. That was a lot of work! And in most workflows, you probably aren't going to be solving these by hand. So let's try using a bit of Python to find the eigenvalue/vector pairs for us:

In [63]:
import numpy as np
from scipy.linalg import eig
A = np.array([[3,2,4],[2,0,2],[4,2,3]])
u, v = eig(A)

In [64]:
for i in range(3):
    print('Eigenvalue: {0:.1f} and eigenvector: {1}'.format(u[i], v[:, i]))

Eigenvalue: -1.0+0.0j and eigenvector: [-0.74535599  0.2981424   0.59628479]
Eigenvalue: 8.0+0.0j and eigenvector: [0.66666667 0.33333333 0.66666667]
Eigenvalue: -1.0+0.0j and eigenvector: [-0.20756326 -0.77602137  0.59557394]


You may notice that their eigenvector aren't exactly the same as ours. The only one that is spot on is the eigenvector associated with $\lambda=8$. But they should meet the criteria specified above.

In [65]:
i = 2
s = v[0, i]
t = v[2, i]
try:
    np.testing.assert_almost_equal(-2*s - 2*t, v[1,i])
    print('This eigenvector meets the specified criteria')
except:
    print('Something is wrong with the specified eigvector')

This eigenvector meets the specified criteria


In summary:

* Find the eigenvalues using the formula $\det{A-\lambda I} = 0$
* For matrices with unique eigenvalues, solve the system of equations to find the corresponding eigenvectors
* For matrices with duplicate eigenvalues, find the constraints on all possible eigenvectors and find a representative one.

Sources:

[MIT](https://ocw.mit.edu/courses/mathematics/18-03sc-differential-equations-fall-2011/unit-iv-first-order-systems/matrix-methods-eigenvalues-and-normal-modes/MIT18_03SCF11_s33_8text.pdf) <br>
[Trinity College Dublin](https://www.scss.tcd.ie/~dahyotr/CS1BA1/SolutionEigen.pdf) <br>
[Imperial College London](wwwf.imperial.ac.uk/metric/metric_public/matrices/eigenvalues_and_eigenvectors/eigenvalues2.html
) <br>
[Oregon State](https://math.oregonstate.edu/home/programs/undergrad/CalculusQuestStudyGuides/vcalc/eigen/eigen.html) <br>
[Lamar](http://tutorial.math.lamar.edu/Classes/DE/LA_Eigen.aspx)

# Find the inverse matrix

By definition, the inverse matrix of an m x m matrix is the matrix that returns the identity matrix when multipled by the original matrix:

$$A A^{-1} = \textbf{I} $$

For 2 x 2 matrices, there is a shortcut. If

$$A = 
  \left[ {\begin{array}{cc}
   a & b\\
   c & d\\
  \end{array} } \right]$$
  
Then the inverse matrix $A^{-1}$ is given by:

$$A^{-1} = \frac{1}{ad - bc}
  \left[ {\begin{array}{cc}
   d & -b\\
   -c & a\\
  \end{array} } \right]$$

For higher dimensions, you can find the inverse matrix by performing matrix operations on the original matrix A and the identity matrix I until the original matrix is the identity matrix:

$$
  \left[ {\begin{array}{cccccc}
   a_{11} & a_{12} & a_{13} & | 1 & 0 & 0\\
   a_{21} & a_{22} & a_{23} & | 0 & 1 & 0\\
   a_{31} & a_{32} & a_{33} & | 0 & 0 & 1\\
  \end{array} } \right]$$

Let's use numpy to find the inverse matrix of our given array:

In [68]:
A1 = np.linalg.inv(A)
print(A1)

[[-0.5    0.25   0.5  ]
 [ 0.25  -0.875  0.25 ]
 [ 0.5    0.25  -0.5  ]]


In [69]:
print(A)

[[3 2 4]
 [2 0 2]
 [4 2 3]]


# Find the matrix exponential

The matrix exponential is a convenient way to solve linear homogeneous systems of equations. Suppose we have a system that can be written as:

$$\textbf{X'} = A \textbf{X} (t) $$

The solution can be written as:

$$\textbf{X} (t) = e^{tA} \textbf{C}$$

where $\textbf{C}$ is an n-dimensional vector of constants.

For the case of a diagonal matrix, its very easy to define matrix exponential. For example, given the matrix

$$A = 
  \left[ {\begin{array}{cc}
   3 & 0\\
   0 & 2\\
  \end{array} } \right]$$
  
The matrix exponential is

$$A = 
  \left[ {\begin{array}{cc}
   e^{3t} & 0\\
   0 & e^{2t}\\
  \end{array} } \right]$$

However, this is not the case when your matrix is no longer diagonal. There are a few easy shortcuts you can memorize if your matrix has a specific form. For instance, if your matrix is of the form:

$$A = 
  \left[ {\begin{array}{cc}
   a & 1\\
   0 & a\\
  \end{array} } \right]$$
 
Then the matrix exponential will be:

$$A = 
  \left[ {\begin{array}{cc}
   e^{at} & te^{at}\\
   0 & e^{at}\\
  \end{array} } \right]$$

However, you may not want to invest all those brain cells on memorizing multiple cases. There is a method for finding the exponential matrix when your matrix is *diagonizable*. A matrix is diagonalizable when there are no repeat eigenvalues. In this specific case, the matrix exponential is given by:

$$S e^{Dt} S^{-1} $$

where D is the diagonal matrix:

$$D = 
  \left[ {\begin{array}{cccc}
   \lambda_1 & 0 & ... & 0\\
   0 & \lambda_2 & ... & 0\\
   \vdots & \vdots & & \vdots \\
   0 & 0 & ... & \lambda_n \\
  \end{array} } \right] = S^{-1}AS$$
  
and S is a matrix where is column is composed of the eigenvectors of matrix A.

Take, for example, the matrix:

$$A = 
  \left[ {\begin{array}{cc}
   3 & 5\\
   1 & -1\\
  \end{array} } \right]$$
  
We find that the eigenvalues are 4 and -2 with the corresponding eigenvectors (5,1) and (-1, 1), respectively. This gives us the matrices:

$$S = 
  \left[ {\begin{array}{cc}
   5 & -1\\
   1 & 1\\
  \end{array} } \right],
  S^{-1} = \frac{1}{6}
  \left[ {\begin{array}{cc}
   1 & 1\\
   -1 & 5\\
  \end{array} } \right]$$
  
with a little matrix math,

$$e^{At} = \frac{1}{6}
  \left[ {\begin{array}{cc}
   5e^{4t} + e^{-2t} & 5e^{4t} - 5e^{-2t}\\
   e^{4t} - e^{-2t} & e^{4t} + 5e^{-2t}\\
  \end{array} } \right]$$

If you are unlucky enough to get a non-diagonalizable matrix, then you're going to have a grand time finding the answer. We won't cover that here, but the sources below will give you an idea where to start.

Sources:

[Math24](https://www.math24.net/method-matrix-exponential/) <br>
[Millersville](http://sites.millersville.edu/bikenaga/linear-algebra/matrix-exponential/matrix-exponential.html)

# Find the singular value decomposition

Singular value decomposition (SVD) is a method to "simplify" the information in a given matrix. Unlike the operations explained above, SVD can be performed on rectangular matrices (matrices that aren't m x m).

SVD can be used to:

* Calculate the pseudoinverse
* Perform feature reduction
* Perform principle component analysis

The SVD for an n x p matrix is calculated by:

$$A_{nxp} = U_{nxn}S_{nxp}V^T_{pxp}$$

where n is the number of features (columns) and p is the number of observations (rows). To calculate,

* The eigenvectors of $AA^T$ make up the columns of U
* The eigenvectors of $A^TA$ make up the columns of V
* The singular values in S are the square roots of the eigenvalues of $AA^T$ or $A^TA$ in descending order arranged diagonally.

For example:

$$A = 
  \left[ {\begin{array}{cc}
   1 & 2\\
   2 & 1\\
   0 & 0\\
  \end{array} } \right]$$
  
$AA^T$ is given by:

$$AA^T = 
  \left[ {\begin{array}{cc}
   1 & 2\\
   2 & 1\\
   0 & 0\\
  \end{array} } \right]
  \left[ {\begin{array}{ccc}
   1 & 2 & 0\\
   2 & 1 & 0\\
  \end{array} } \right] = 
  \left[ {\begin{array}{ccc}
   5 & 4 & 0\\
   4 & 5 & 0\\
   0 & 0 & 0\\
  \end{array} } \right]
  $$

The eigenvalues of $AA^T$ are found to be 9, 1, and 0, with the corresponding eigenvectors (1,1,0), (1,-1,0), and (0,0,1). This gives the matrix U (after normalization):

$$U = \frac{1}{\sqrt{2}}
  \left[ {\begin{array}{ccc}
   1 & 1 & 0\\
   1 & -1 & 0\\
   0 & 0 & 1\\
  \end{array} } \right]$$

$A^TA$ is given by:

$$AA^T = 
  \left[ {\begin{array}{ccc}
   1 & 2 & 0\\
   2 & 1 & 0\\
  \end{array} } \right]
  \left[ {\begin{array}{cc}
   1 & 2\\
   2 & 1\\
   0 & 0\\
  \end{array} } \right] = 
  \left[ {\begin{array}{cc}
   5 & 4\\
   4 & 5\\
   \end{array} } \right]
  $$

The eigenvalues of $A^TA$ are found to be 9, and 1, with the corresponding eigenvectors (1,1) and (1,-1). This gives the matrix V (after normalization):

$$V = \frac{1}{\sqrt{2}}
  \left[ {\begin{array}{cc}
   1 & 1\\
   -1 & 1\\
  \end{array} } \right]$$

Finally, the S matrix is given by

$$S = 
  \left[ {\begin{array}{cc}
   3 & 0\\
   0 & 1\\
   0 & 0\\
  \end{array} } \right]$$

We can do the same thing computationally taking advantage of the `numpy` package `svd`:

In [192]:
A = np.array([[1,2],[2,1],[0,0]])
U, S, VT = np.linalg.svd(A)
Si = np.zeros(A.shape)
Si[0:S.shape[0], 0:S.shape[0]] = np.identity(S.shape[0]) * S
V = np.transpose(VT)
UT = np.transpose(U)

print('U: {}\n'.format(U))
print('S: {}\n'.format(Si))
print('V: {}'.format(V))

U: [[-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]

S: [[3. 0.]
 [0. 1.]
 [0. 0.]]

V: [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


Let's check if SVD holds up to its claims. We should be able to recover the original matrix using the U, S, and V matrices.

In [190]:
print(np.dot(np.dot(U,Si),VT))

[[1. 2.]
 [2. 1.]
 [0. 0.]]


## Pseudoinverse

The SVD transform can also be used to calculate a matrix known as the pseudoinverse. The psuedoinverse, like its counterpart, the inverse, returns the identity matrix when multiplied by the original matrix:

$$A A^{\oplus} = I $$

The pseudoinverse operation, however, doesn't require the original matrix to be square. If the original matrix is of dimensions m x n, then the dimensions of the pseudomatrix are n x m. The pseudomatrix is calculated by:

$$A^{\oplus} = V S^{\oplus} U^T $$

But uh oh. The calculation of the pseudomatrix requires that we know the pseudomatrix of the singular matrix. How do we get that? Well, since the singular matrix is a diagonal matrix, you simply invert the scalar values of the entries e.g.:

$$S = 
  \left[ {\begin{array}{cc}
   3 & 0\\
   0 & 1\\
   0 & 0\\
  \end{array} } \right],
  S^{\oplus} = 
  \left[ {\begin{array}{ccc}
   \frac{1}{3} & 0 & 0\\
   0 & 1 & 0\\
  \end{array} } \right]$$

In [205]:
Di = np.zeros(np.transpose(A).shape)
Di[0:S.shape[0], 0:S.shape[0]] = np.linalg.inv( np.identity(S.shape[0]) * S)
Ai = np.dot(np.dot(V,Di), UT)
print('pseudoinverse of A:\n{}'.format(Ai))

pseudoinverse of A:
[[-0.33333333  0.66666667  0.        ]
 [ 0.66666667 -0.33333333  0.        ]]


We can verify that our pseudoinverse is working correctly if it returns the identity matrix:

In [209]:
print('Is this the identity matrix?:\n{}'.format(np.dot(A,Ai)))

Is this the identity matrix?:
[[ 1.00000000e+00 -3.33066907e-16  0.00000000e+00]
 [ 2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


The first two elements of the diagonal correspond to the elements of the identity matrix, but the last one doesn't (it's zero). This is due to the fact that our original matrix had an empty row. So we *almost* get a full identity matrix. Another reason why it's called the pseudoinverse.

## Dimensionality reduction

A common problem in machine learning methods is the need to reduce the dimensionality of a dataset e.g. you have more features (columns) than observations (rows). It is possible to reduce your feature set into a smaller set of features most relevant to the problem. There are multiple approaches to do this, and SVD is one of them.

To do this, we take a subset of the singular values in S and V:

$$B = U S_k V^T_k$$

This doesn't work well with our previous example, because we only had two columns or features.

SVD is also used as a substep in more complicated dimensionality reduction methods like PCA.

Sources:

[machine learning mastery](https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/) <br>
[MIT](http://web.mit.edu/be.400/www/SVD/Singular_Value_Decomposition.htm) <br>
[Carnegie Mellon](https://www.cs.cmu.edu/~venkatg/teaching/CStheory-infoage/book-chapter-4.pdf)